# Generated by Django 4.2 on 2026-05-05 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField(unique=True)),
                ('approved_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('drawn', 'Drawn')], default='open', max_length=10)),
                ('winner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('winner_ticket_number', models.IntegerField(blank=True, null=True)),
                ('drawn_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=150)),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UPIInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(max_length=100)),
                ('payee_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=150)),
                ('qr_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('upi_reference', models.CharField(blank=True, max_length=255)),
                ('payment_screenshot', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('ticket_number', models.IntegerField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.batch')),
                ('selected_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
